### ISSUE TITLE
Version 2.1.0 classes have changed, style breaks

### ISSUE THREAD

**Issue by dhamaris** [ec-europa/europa-component-library#1008]
### Expected behavior
I changed my css and js (ecl-ec-preset-website) version from 1.2.0 to 2.1.0 and refresh my browser.
My classes should be the same.
### Actual behavior
Classes have changed, and layout is broken. See pictures below.
### Steps to reproduce the issue
Before upgrading:
![image](https://user-images.githubusercontent.com/1392485/52401527-29833f00-2ac2-11e9-8a77-7210cb1bda6a.png)
After upgrading:
![image](https://user-images.githubusercontent.com/1392485/52401545-37d15b00-2ac2-11e9-9734-b7dbfc735f51.png)
![image](https://user-images.githubusercontent.com/1392485/52401584-4e77b200-2ac2-11e9-8709-532db691e261.png)

**Comment by degliwe** [comment]
Hi @dhamaris thank you for your comment.

ECL is following semantic versioning https://semver.org/
The fact that the current version of ECL  is v2.* means that it is not compatible with ECL v1.* (Major version)
From that point on you have to options:

1. Stick to the latest v1.* for the time being (v1.3.0) and then the transition should be easy.
2. Upgrade to v2.* , meaning that you'll have to update your markup

I hope this clarify the situation.

**Comment by dhamaris** [comment]
Hi @degliwe, thanks for your explanation, I understand what a major version does, but my question is:

Is there is any naming convention for css classes you could follow from the beginning and stick to it? I understand there are major changes from v1 to v2, but is it possible to keep css classes names? Be mindful that if you release a major version every 10 months, and it breaks the whole layout of dozens of applications, that means a month of extra work depending on the application.

**Comment by dhamaris** [comment]
Another thing is, if I stick to the v1 and find bugs there, I won't have support, won't I?
I think I don't have much choice but to switch to v2 at some point.

**Comment by degliwe** [comment]
> Another thing is, if I stick to the v1 and find bugs there, I won't have support, won't I?

As you can see https://github.com/ec-europa/europa-component-library/releases/tag/v1.3.0  was released in December so we are still providing support.

> I think I don't have much choice but to switch to v2 at some point.

Well isn't it the case for any other framework that you are using?

**Comment by degliwe** [comment]
> Hi @degliwe, thanks for your explanation, I understand what a major version does, but my question is: Is there is any naming convention for css classes you could follow from the beginning and stick to it?

We are following strict naming conventions http://getbem.com/naming/ for which we have automated check using https://github.com/simonsmith/stylelint-selector-bem-pattern
When we have a good reason to rename a classe, we don't take it lightly and this it what triggers the need for a major version.
We would love to get everything right from the start but we don't.

> I understand there are major changes from v1 to v2, but is it possible to keep css classes names?

That's one of the reason to embrace semantic versioning so that we communicate clearly to everyone involve which versions are backward compatible. 
We qualify a change as major for one of the following reasons:
- markup changed (html)
- classes changed (new classe, new name)
- js api changed 

> Be mindful that if you release a major version every 10 months, and it breaks the whole layout of dozens of applications, that means a month of extra work depending on the application.

We truly are, that's why we try to avoid major changes as much as we can.
The web evolves quickly and in order to remain relevant, become more accessible, expand browser support we have to make markup changes, see the example with buttons below:

Button v1.*
`
<button type="submit" class="ecl-button ecl-button--call ecl-button--caret-right">Call-to-action</button>
`

Button v2.*
`<button type="submit" class="ecl-button ecl-button--call"><span class="ecl-button__container"><span class="ecl-button__label"
      data-ecl-label="true">Call to action button</span><svg focusable="false" aria-hidden="true" data-ecl-icon="true"
      class="ecl-button__icon ecl-button__icon--after ecl-icon ecl-icon--xs ecl-icon--rotate-90">
      <use xlink:href="/static/media/icons.cbfd6efe.svg#ui--corner-arrow"></use>
    </svg></span></button>`

We replaced font icons with svg's in order to be more accessible and avoid random support form IE, so we need a container for the svg, we've also added proper aria attributes...

Understand that ECL was still young in v1.* so it's natural at the beginning to have important changes, now we reached v2.* which we hope will last much longer than v.1.* and we have no plan for a v3.* yet.

for references https://medium.com/@lukaszholeczek/migration-from-bootstrap-3-to-bootstrap-4-4ec63a1dd8b1  as you can see this situation is not uncommon, still it requires extra work but be sure that we always keep that in mind and try to avoid breaking changes as much as possible.

**Comment by dhamaris** [comment]
Thanks for the thorough explanation, I am sure that you are doing as much as possible to reduce breaking changes, and that at early stages things are a bit more unstable.
Is is possible to have a listing of breaking changes for this V2, as in the example from Bootstrap 4 you showed me? That would be very useful. Something like:

```
Typography
.page-header - dropped
.dl-horizontal - dropped
<blockquote> to .blockquote
Grid
.col-xs-* to .col-*
.col-*-offset-* to offset-*
.col-*-push-* - dropped
.col-*-pull-* - dropped
Buttons
.btn-default to .btn-secondary
.btn-xs - dropped
Button group
.btn-group-justified to btn-group.d-flex
.btn-group-xs - dropped
Breadcrumbs
.breadcrumb > li to .breadcrumb > li.breadcrumb-item
```

Having a record of these changes would save us tons of time and won't take ECL developers longer than writing a comment.

**Comment by degliwe** [comment]
I agree, we've been unable to provide a migration documentation.
We've learned that we should document the changes more thoroughly as they happen.
Unfortunately this is not as simple as "writing a comment".

This is the global diff between v1 and v2 
https://github.com/ec-europa/europa-component-library/compare/v1...v2

I've created a ticket representing the creation of such a migration documentation
https://webgate.ec.europa.eu/CITnet/jira/browse/INNO-1330
I understand that you've already invested time in comparing v1 and v2, your contribution here is very welcome.
