### ISSUE TITLE
ec-component-navigation-menu

### ISSUE THREAD

**Issue by bmdoherty** [ec-europa/europa-component-library#1011]
Hi folks,

We have started to use v1.3.0 @ecl/ec-preset-website within a react single page application. When using the navigation menu component (https://v1--europa-component-library.netlify.com/ec/components/detail/ec-component-navigation-menu) we see behavior that is more in common with a traditional multi-page application. 

### Expected behavior (for single page app)
Menu closes on clicking a menu item
### Actual behavior
Menu stays open

We can work around this, but it raises some questions for us.

1. Is this as intended behavior. ie is it assumed (so far) that consumers of ECL will be multipage applications?
2. Will such generic components be reusable in v2, or will we have to refactor to use v2 components eventually
3. Are there any resources available to help us use ECL within a single page (react) application? 
4. Any known issues with the approach we are taking etc. Or anything in the pipeline that you think would be useful to us. 

many thanks for your help

**Comment by yhuard** [comment]
Hi @bmdoherty, thank you for opening this issue!

> 1. Is this as intended behavior. ie is it assumed (so far) that consumers of ECL will be multipage applications?

Indeed, the current versions of ECL have been designed almost exclusively for web **sites** (what you refer to as "multipage applications"), ignoring web **apps**. This is something we are willing to change in the future, in order to cover more use cases like web apps (both internal and external). I'll report your case in our weekly meeting with designers. 

> 2. Will such generic components be reusable in v2, or will we have to refactor to use v2 components eventually

v2 will most probably offer a similar component (though it doesn't have it yet) but the markup and the styles could be slightly different. We can't guarantee that the upgrade will be seamless.

> 3. Are there any resources available to help us use ECL within a single page (react) application?

Not yet. As you may have noticed, we use React internally since v2, but we don't publish these React components. For business reasons, we have to focus on building the most technology-agnostic components: that's why we have BEM CSS classes and don't use CSS-in-JS, that's why we provide "vanilla" JS and not React components... We have to support projects using Angular, Twig, React, Vue and even Spring. At our level, we can't just say "we build React components and you have to adapt them to your case". The only common language is HTML, CSS and vanilla JS. Now, if a team comes with an integration of ECL components in React, we would be happy to share it. For example, here's an Angular implementation of ECL components: https://euidev.ecdevops.eu/screen/app/ecl. Work is also in progress for building Twig components: https://github.com/ec-europa/ecl-twig

Now, I think the most straightforward way for you to start using the ECL visual identity is to embed the stylesheets we provide, copy the HTML markup into your JSX components and **ignore** the vanilla JS. It's often more complicated to try to reuse the existing vanilla JS in React than to reimplement its behavior. E.g. switching classes on click in React is almost natural :)

> 4. Any known issues with the approach we are taking etc. Or anything in the pipeline that you think would be useful to us.

I'll let you know if we have some useful information to share. Meanwhile, if you have technical issues, don't hesitate to create GH issues. We'd be happy to help.

Anything you can report to help us improve ECL will be appreciated!

**Comment by bmdoherty** [comment]
thanks @yhuard, much appreciated. Just using the stylesheets and HTML is how we have approached it so far, megamenu was the first case where we thought we would ask the question.

thanks again for your help and good work with the ECL
