### ISSUE TITLE
Language list - Overlay initialization

### ISSUE THREAD

**Issue by df-git** [ec-europa/europa-component-library#1278]
Dear All,
I am trying to initialize a basic HTML with the ECL v2.10.1 but I cannot find any documentation on how to initialize the "Language list overlay" page structure element.
The element is correctly working in the template > standard example but I can't find how to initialize it on my html (created following the guidelines at https://ec.europa.eu/component-library/ec/getting-started/).

Can you give some advice?
Thank you in advance

**Comment by yhuard** [comment]
Hi!

In ECL v2.10.1, the language list overlay is working in the standard example only because we manually attach a custom event listener and all the JS behaviour (toggling classes/attributes).

The good news is that we've recently merged (https://github.com/ec-europa/europa-component-library/pull/1267) the auto initialisation of this feature, which means that with ECL v2.11.0 (to be released this week), you won't have to write any custom code.

I hope that helps!

**Comment by df-git** [comment]
Thank you very much
