### ISSUE TITLE
Information about ECL v.2.12 major changes in header/footer

### ISSUE THREAD

**Issue by df-git** [ec-europa/europa-component-library#1344]
Dear ECL v2 team,
We are developing web application using the ECL v2.11. The application is almost ready to be deployed.
Now we discovered that in this new release (v.2.12) the header and in particular footer changed a lot from v.2.11.

We would like to know what should we do. Do we need to adapt our application to the new footer and header?
Should we need to expect other major changes in the look and feel of the UI?

Thank you in advance

**Comment by yhuard** [comment]
Hi @df-git 

According to the [IPG](https://wikis.ec.europa.eu/display/WEBGUIDE/02.+EC+branded+standardised+websites+design),

> By end of 2020, all Commission websites must implement the new design components.

which means that in the meantime, you can still use the "old" site header, page header and footer.

ECL v2.12.0 still ships these "old" components but they are not documented anymore, we favour the new ones. 

We are working on the new page headers for the new templates (core, standardised, harmonised). These new page headers will contain the new breadcrumbs as well (this should answer your question https://github.com/ec-europa/europa-component-library/issues/1346).

New site headers, page headers and footers: these are the main changes you will have to worry about in the near future. I don't know any other big changes coming soon.

Also, we are currently discussing how to keep previous versions of the website online so you can still find the documentation for the version of the ECL you're working with. The most probable solution is that we will publish copies of the website under their tag version, like: https://ec.europa.eu/component-library/v2.11.0/ (doesn't work yet) It's still under discussion but I feel it will soon become a high priority.

Please let me know if you need more information!

**Comment by df-git** [comment]
Thank you for the answer. 
When do you expect to have something stable in terms of header/footer?

**Comment by yhuard** [comment]
So far, we have:
- implemented and documented (even if just succinctly) the new page headers and footers for both core and standardised templates
- implemented but not yet documented the page header and footers of the harmonised group 1 and group 2 templates; we will push the docs soon (this week)

What's remaining:
- the page header (including the breadcrumb) for all the templates that need one (harmonised + standardised); we are currently working on the standardised page header, harmonised page header will follow soon, these 2 should be delivered next week or the week after
- harmonised group 3: a new group of websites will get its own template, you can expect to have a new site header, a new page header and a new footer for this group. So far, it's still unclear what it's going to look like...

Also, please note the navigation menu (e.g. in the standardised site header) is not working yet, that's because UX and design are still working on it and we don't know yet how it's going to work exactly.

As you can see, there are many tasks in progress and I hope we'll be able to deliver the finalised components by the end of next month, but I can't guarantee anything.

**Comment by df-git** [comment]
Thank you very much for your clear answer
