### ISSUE TITLE
Showcase pages - Error 404 on v.2.12 pages

### ISSUE THREAD

**Issue by df-git** [ec-europa/europa-component-library#1347]
Dear ECL v2 team,
While browsing the components/templates/pages of the ECL v.2.12 there are a lot of errors "404 page not found",
Can you please check?

**Comment by yhuard** [comment]
Hi @df-git 

I've encountered some random 404s as well. 

Some 404s are due to the browser's cache: try to reload the page without the cache. If they still appear, can you please share with us the link to the pages that return a 404? 

Other 404s seem more random and disappear automatically even without flushing the cache. I'll contact the devops to check if there's anything we can do about them.

Thank you for reporting the issue!

**Comment by yhuard** [comment]
Just got a feedback from the devops: one of the server was down, they've restarted it, now I don't get these random 404s anymore.

Can you confirm you don't have 404s either? Thank you!

**Comment by df-git** [comment]
Now it is working, thank you
