### ISSUE TITLE
New header harmonised (v2.26.0) shows cut login box

### ISSUE THREAD

**Issue by dhamaris** [ec-europa/europa-component-library#1570]
### Expected behavior
Login box: Logout link should be displayed properly
### Actual behavior
Login box: Logout link is cut by menu. It doesn´t happen when class name element is there.
### Steps to reproduce the issue
Go to example in catalog using a big screen:
https://ec.europa.eu/component-library/playground/ec/?path=/story/components-site-headers-harmonised--group-1
Using developer tools in Chrome, remove class name element as it is not mandatory.
Open login box. Logout link appears to be hidden under the main menu elements.

**Comment by kalinchernev** [comment]
Please add screenshots of the issue

**Comment by dhamaris** [comment]
![image](https://user-images.githubusercontent.com/1392485/79103529-0d85c800-7d6d-11ea-963f-95f27923a2a0.png)

As you see in the image attached, logout link appears to be hidden under main menu.

Thanks

**Comment by kalinchernev** [comment]
@dhamaris thank you for the visual, makes it easier to see the issue!
The menu with log in and log out links have z-index of value 15 which matches dropdown value of [ECL's variables](https://github.com/ec-europa/europa-component-library/blob/v2-dev/src/systems/ec/implementations/vanilla/packages/ec-base/variables/_z-index.scss).

The reference implementation in https://ec.europa.eu/component-library/playground/ec/?path=/story/components-site-headers-harmonised--group-1 is that the element below the menu does not have a z-index in order to allow for the menu to go above.

![nav-issue](https://user-images.githubusercontent.com/1923476/79323657-c9322d80-7f0e-11ea-971c-b02ead61cf7a.png)

Could you please double-check whether the blue area element is not having a value of z-index higher than 15 on your side?

Edit: `ecl-menu__list` is `z-index: 21;` in https://ec.europa.eu/component-library/v2.26.0/playground/ec/?path=/story/components-site-headers-harmonised--group-1 version of the menu component.

**Comment by dhamaris** [comment]
Yes, ecl-menu__list has a z-index of 21, so it is higher than the 15 from the account menu and goes above:

![image](https://user-images.githubusercontent.com/1392485/79885779-d57b2680-83f7-11ea-8ea9-fe3aaf8693ee.png)

**Comment by emeryro** [comment]
Follow-up ticket: https://webgate.ec.europa.eu/CITnet/jira/browse/FRONT-1134

**Comment by emeryro** [comment]
The issue has been fixed, it will be part of next release (2.29)
