### ISSUE TITLE
Header search box question

### ISSUE THREAD

**Issue by dhamaris** [ec-europa/europa-component-library#1576]
Hi, can header search box (Europa Search box referenced [here](https://ec.europa.eu/component-library/ec/harmonised-templates/site-header/group1/)) be used to search content from my website? I am not sure if this search box is supposed to search in all EC websites or it can be used for just the website where it belongs. We need to use it just for internal content.

![image](https://user-images.githubusercontent.com/1392485/79104212-6bff7600-7d6e-11ea-8cad-e917d6f0fced.png)

Thanks

**Comment by kalinchernev** [comment]
@dhamaris please refer to the do's and don'ts of the variant relevant for your project https://ec.europa.eu/component-library/ec/harmonised-templates/site-header/group1/ 

If guidelines are not clear enough, please submit a request to Europamanagement@ec.europa.eu as it's a question of corporate decision rather than a technical one.
