### ISSUE TITLE
Rebuild Select without calling autoInit()

### ISSUE THREAD

**Issue by dhamaris** [ec-europa/europa-component-library#2091]
Hi, I have a set of 3 selects, where each one of them depends on the selection on another one (without submitting any form). The first one is a single, and the two below are multiselects. 

![image](https://user-images.githubusercontent.com/1392485/120503205-61b19880-c3c3-11eb-9d08-50b6ca5b95ef.png)

I already got sorted out the problem of reacting to a custom eventhandler [here](https://github.com/ec-europa/europa-component-library/issues/2078).
My question now is how can I rebuild each select without having to reload the page or calling AJAX.
This is the trick I am using at the moment but I am not happy with it:

```
function(options, selector, initialize){
	var arrOptions = [];
	var counter = 0;
	for(var key in options){
	     if (options.hasOwnProperty(key)) {
	    	var selection = counter == 0 ? "selected" : "";
	        arrOptions.push("<option " + selection + " value='"+ key +"'>" + options[key] + "</option>");
	        counter++;
	    }
	}

	selector.get(0).innerHTML = arrOptions;
	if(initialize){
		var select1 = new ECL.Select(selector[0]);
		select1.init();
		select1.destroy();
		select1.init();
	}

};
```
Do you have any ideas? Do you think I should go for AJAX and forget about this? Could we have a "rebuild" method that reconstructs the divs with the current options? Or it is something that might be available in the future?

Thank you

**Comment by planctus** [comment]
Well, for sure what you're doing is really "custom", the component per se is not meant to create this kind of interactions between different instances, so surely you need to have your own script handling them.
If i get it correctly your request is to have on our side a "reaction" in the moment when something changes in the options of a select multiple so that the component would be rebuilt, right?
Should be fairly easy, but it's not going to be far from what you're doing, because the "rebuild" method is basically the init() function, anyway on our side we would have an observer that would react to any addition or removal of children of the select.
Something like this:
```
  initObserver() {
    if ('MutationObserver' in window) {
      const self = this;
      const observer = new MutationObserver(function() {
        self.destroy();
        self.init();
      });

      observer.observe(this.element, {subtree: true, childList: true});
    }
  }

  destroyObserver() {
    if (this.observer) {
      this.observer.disconnect();
    }
  }
```
But yeah, this is a bit what you are already doing on your side and it's not maybe such a common case to justify setting up an observer on our side, we can consider it but i cannot promise this would be taken into account.

**Comment by dhamaris** [comment]
Thank you for your answer, the less awkward solution was to profit from the event listeners themselves, as we could already set up custom listeners: https://github.com/ec-europa/europa-component-library/issues/2078
So in the end whenever the first select changes, our listener is called and rebuilds the second select from scratch using js, and then calls ECL.init on it, so no need to call destroy as the select component will get removed every time we need to build it again.
