### ISSUE TITLE
Social-media-share vanilla dependency missing

### ISSUE THREAD

**Issue by papegaill** [ec-europa/europa-component-library#2671]
Hi, 

A dependency is missing here `@ecl/vanilla-layout-grid`

https://github.com/ec-europa/europa-component-library/blob/0a2584bac657e40bf6ae2f6df46f7fe3b109a706/src/implementations/vanilla/components/social-media-share/package.json#L10

**Comment by papegaill** [comment]
Shouldn't we add the dependencies for the child components used as well?

`@ecl/vanilla-component-link`
`@ecl/vanilla-component-icon`

**Comment by planctus** [comment]
mmh..first of all these are devDependencies, they are basically meant to ensure that the package will use available resources if used in a development environment (in this case, for compilation), you are right and the layout-grid dep is missing, because that is needed to compile the src scss file.
Why do you consider "link" a child component, though..? The social-media-share css doesn't rely on that as it doesn't rely on the icon css, technically speaking, but i understand that your concern here is more about getting all the css targeting any of the selectors defined by the component, which is what you are currently getting by purging the compiled css, i guess...

**Comment by papegaill** [comment]
Nice if you can add missing `@ecl/vanilla-layout-grid` dependency. 
No more purging, I'm now compiling necessary SASS files and using related TWIG templates. 
Instead of having to manually add the necessary libraries to the component, I thought it would be better to reference this directly in the main ECL package...
