### ISSUE TITLE
Apply ECL on top of Bootstrap-vue

### ISSUE THREAD

**Issue by iliion** [ec-europa/europa-component-library#2757]
Hi. 
I have a website based on VUE (and bootstrap-vue) and I was wondering what is the best way to apply the `ecl` theme and override the already existing scss.

**Comment by planctus** [comment]
Hello @iliion, the question confuses me a bit, bootstrap vue is providing you with the components coming from bootstrap 4, ECL is a deisgn system, as well as bootstrap, and it comes with its own components, markup, etc...
ECL is an agnostic library defining vanilla components using css, js and html, it can be used in any environment, technology but we do only provide an implementation in twig (for drupal, mainly), although we are in the process of releasing a webcomponents implementation as well.
In your case it seems it's not a matter of applying a theme on top of what you have, if you want (and you are allowed) to use ECL for you website, then your markup should reproduce the one defined by ECL, at that point using the ECL resources like css, js would give you the ECL look and feel for your components and pages.

**Comment by iliion** [comment]
hi @planctus yeah I am a bit confused myself too. 
Basically I want to avoid changing the code of the already existing project in VUE and find a non-intrusive  way to inject/add ECL components.

**Comment by planctus** [comment]
vue is not the problem, as said ECL is defining a markup and providing css and js for that, if you implement our components markup in vue you would then be able to add the ECL css and js, but this is something you have to do yourself.

As said, in the near future ECL will be available also as webcomponents, which might fit your use case and be simpler to use since you wouldn't have to reproduce the ECL markup yourself.
But there is no due date for this, we are working on it as a new project, so it might take time for it to reach a certain stability.

**Comment by iliion** [comment]
ok Thank you for your reply. :)
