### ISSUE TITLE
Required Checkbox coded as (optional) in the ECL showcase

### ISSUE THREAD

**Issue by Regine-Lambrecht** [ec-europa/europa-component-library#3006]
### Expected behavior
The [required checkbox legend in the ECL library](https://ec.europa.eu/component-library/ec/components/forms/checkbox/code/), both in the default and invalid version, should not mention "(optional)" in its showcase code. Use the code of the [Playground ](https://ec.europa.eu/component-library/playground/ec/?path=/story/components-forms-checkbox--default) instead.

### Actual behavior
The default and invalid examples, with asterisk, contain the following inside the `<legend>`:
```
<span
      class="ecl-form-label__optional"> (optional)</span>
```

### Steps to reproduce the issue
Open the ECL library showcase :)

**Comment by planctus** [comment]
True, thanks for reporting this, since these examples in the website are retrieved from the "playground", aka storybook, it's always better to use that directly also because there you can customise the look and feel of the component and get the resulting markup.
We will align the source code with the demo in the showcase of the checkbox, anyhow ;)
