### ISSUE TITLE
Media gallery uses list display image in modal rather than image linked to

### ISSUE THREAD

**Issue by kiwimind** [ec-europa/europa-component-library#3213]
### Expected behaviour
When viewing a media gallery, it should be possible to use smaller versions (thumbnails) of the images that will be displayed prior to opening a full sized image when the modal is opened.

### Actual behaviour
Currently if an image is displayed as a thumbnail in the gallery listing, that same image is used in the modal, even when the href on its parent link is set to the full sized image.

### Steps to reproduce the issue
Set the listing display image as a thumbnail with its parent link having its href set to the full sized image. The thumbnail will display in the listing and when clicking on, will display this same thumbnail in the modal, rather than the full sized image.

**Comment by planctus** [comment]
Hello @kiwimind, i don't know which ECL version you are using, but it seems to me that you are expecting a behavior based on an assumption, the fact that the href set on the "thumbnail" has any relation with the image being shown in the overlay.
Instead is only a fallback in case js is not active, that is the reason why those elements are links with an href, the functionality of the ECL gallery is to "move" to the overlay what is defined in the gallery listing items, basically, wether is an image, a video, an iframe.
In v3 we started introducing the picture tag, so that you can pass multiple images, when you click on an "image" the whole markup of the picture tag is cloned into the overlay so that you would use different images at different viewports, if you decide so.
This would not be possible simply grabbing the href of a link, i understand that you might be used to this kind of behavior but that is not how the ECL gallery works.

Having said this, i do see the benefits of using smaller images for the listing and "lazy" loading the big ones in the overlay, we could think of giving the possibility of defining an image to be used only in the listing, as long as we also have the "element" to be then cloned in the overlay and we are able to prevent the loading at page time of the big ones.
This would surely have an impact on the rendering of the overlay, though, potentially a bad one, so as said, we can evaluate this as a "feature request", but with no guarantee that we will really implement it.
Thanks!

**Comment by kiwimind** [comment]
Thanks for the response @planctus 

I fully understand and respect your response and had assumed it could be refactored into something that it isn't. :)

This thought is mainly to avoid loading what could potentially be a lot of large images as thumbnails that may never be viewed full size if the gallery is ignored. Would be very happy to see this added as a feature request. Must be a good thing reducing bandwidth usage until necessary.
