### ISSUE TITLE
How to import ECL module ?

### ISSUE THREAD

**Issue by parktrip** [ec-europa/europa-component-library#3555]
Dear support,

question looks easy but we are currently not able to use the ECL object in our javascript controllers.

It works fine if we add the <script> tag in our HTML, then the ECL object is present, etc ...

But if we try the other method by importing ecl-presets (via an 'import' or 'require' statement), the ECL object is just empty or does not exist.

After having a look at what is inside the @ecl\preset-ec\dist\scripts\ecl-ec.js file, it looks normal we cannot import it as the script only defines a ECL variable and not a module.

However, in this documentation page https://github.com/ec-europa/europa-component-library/blob/v4-dev/docs/javascript.md, it is written "This file contains a JavaScript module called ECL".

which part are we missing here ?

Thank you in advance.

PS: FYI, we are trying to use ECL in a stimulus controller in a symfony app.

**Comment by planctus** [comment]
Hello @parktrip, the problem here is not really about the way the ECL js is bundled, it is an IIFE but for what it matters the script needs to be executed by the browser, that's why when you try to import it or require it this will fail.
We could change the documentation if you find the usage of "javascript module" not correct but in any case you get the information about how to use ECL, including its js in the website: https://ec.europa.eu/component-library/ec/getting-started/.
Thanks
