### ISSUE TITLE
Is last item from list supposed to have a border?

### ISSUE THREAD

**Issue by dhamaris** [ec-europa/europa-component-library#3678]
Hello, I am currently working with ECL 4.6.3, using the EC preset, and my  list of elements is not removing the last border:

![image](https://github.com/user-attachments/assets/29f535c8-b007-4a52-a515-ec6b57961224)

I checked at my css, and i don't see css for setting border-bottom to 0px, only padding, but it gets overwritten:

![image](https://github.com/user-attachments/assets/6840ec15-07b3-4e5e-8042-fc43a1dd3881)

So I have 2 questions:
- Can you, for next releases, also add the rule to set border-bottom to 0 for last-of-type in a way that does not get overwritten? Or is it not intended to be so? I saw that for news at the ec.europa.eu website, they have used a specific class for last items (last-item-column last-item), not sure whether that was added later, or it is just for eu presets:
![image](https://github.com/user-attachments/assets/2b46326b-d86a-4063-a9d5-7ad960523af9)

- Where does all this css from @ecl/node_modules come from? I am working with a drupal project and only added the basic css files: default, utitlities, ecl-ec...

Thanks a lot,
Dámaris

**Comment by planctus** [comment]
Hi @dhamaris, although we are here to help i would recommend you to take a look at the basics of the ECL usage here: https://ec.europa.eu/component-library/ec/getting-started/
We do provide multiple packages, the list is available in every release, but most of the users rely only on the ec or eu preset package, since they contains all the resources including icons, logos, css and js.
These two packages are:

- @ecl/preset-ec
- @ecl/preset-eu

In the dist folder you have the styles folder, inside there is the main css file (ecl-eu.css or ecl-ec.css) and many other stylesheets which are "optional", meaning that you can use it or not depending on your needs, you can find a bried description of the available stylesheet in the aforementioned page in the website.

The confusion here mainly comes from the ecl-{ec/eu}.default.css, one of the optional css, which is meant to be used for generic content that you want to be styles as ECL without using its selectors, it's a solution used in the drupal projects for the rich text editor content, it styles some elements when inside an .ecl wrapper and yes, it duplicates many of the css rules defined in the main css for the components markup.

So, back to the list, we do not reset the border for the last item when using the "divider", but i understand this might be beneficial in case you have a following element coming with a border top, as it happens with the pager, so we might consider introducing an option to remove the last border.
For the padding, since we don't remove the border this is still needed in the divider variant, that's why you see the rule resetting it being "overridden".

Hope it clarifies, would you happy with an option (this would then need to be integrated in the cms) so that you can selectively remove the border from the last item only when needed?

**Comment by dhamaris** [comment]
Hi @planctus, thanks for the thorough response, and sorry that I was squizing several questions into one ticket. I will add more tickets separating topics. 

Just to clarify the one concerning the overwriting issue: I understand the function of default.css, and I agree that there will be duplicity or css overwritten. 
My confusion had to do with unordered-lists.scss and the fact that the same rule gets overwritten **in the same css** (sorry for the misleading screenshot, let's forget about default.css)

![image](https://github.com/user-attachments/assets/450c7cd3-ea7c-4519-8c28-51a03c5726fb)

Why is rule for last item not overwriting the others, as it is a more special case? I mean this one:
```
.ecl-unordered-list__item:last-of-type {
    padding-bottom: 0;
}
```
Concerning the border-bottom: 
You don't need to make changes for this, if the normal usage is to have dividers down to the last element it is ok with me. I am not working with cms here, it is a drupal view, that lists items, but i could add a special class for the last item in the twig loop. For the moment, the easiest thing for me is a custom css:

![image](https://github.com/user-attachments/assets/2d08c2cd-3e79-43b0-a020-21068cfc73e5)

Thanks a lot!

**Comment by planctus** [comment]
Well, in this case it's not css specificity, the two selectors have just the same, but the one we use to keep the padding for the divider variant comes later in the css.
If you're ok with your custom css solution for this, no reasons to dig more into it :)

**Comment by dhamaris** [comment]
Ok, my bad, I failed to see that if you inverted the order, the last element in dividers lists would have the border closer than its siblings, which is wrong, so as you say, my custom css just does the trick. 

Thanks a lot for your patience! I close this ticket
