### ISSUE TITLE
Is there an unminimized js version for debugging? 

### ISSUE THREAD

**Issue by dhamaris** [ec-europa/europa-component-library#3698]
Hello, I am working with ECL 4.6.3 and I trying to debug some odd behaviour (only happening in Drupal) and it is difficult with the minimized version. 

![image](https://github.com/user-attachments/assets/81eee25d-7dfb-4f7a-8ec9-4297b6b068f7)

Do you know how can I have a version with the function names? It would help us a lot

Thanks

**Comment by planctus** [comment]
@dhamaris, the problem is not the minification of the js, you could easily unminify it using any online tool, the js we distribute is transpiled, we write classes in ES6, the js you get is ES5, so there is no way to go back to the source code, the way to make the code debuggable in this case is to generate a source map, which is something we do in development but not in production.
So, currently you could fetch the repo, install deps using yarn and after that you would have in the presets folders (src/presets/ec/build and src/presets/eu/build) an unminified file with the sourceMap, you can take that and replace it in your application temporarily to be able to debug it, when using the devtool you would be able to see the source code mapped to our bundled js.
The reason why this source map is not available in production is mainly for security and performance reasons. Hope it helps, thanks.

**Comment by dhamaris** [comment]
I will do, thanks a lot!
