### ISSUE TITLE
ESM - script and images

### ISSUE THREAD

**Issue by diogoslack** [ec-europa/europa-component-library#3741]
Hello,

I'm trying to use the ECL in a Symfony project using the [AssetMapper](https://symfony.com/doc/current/frontend/asset_mapper.html) which implements an [importmap](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script/type/importmap), instead of having a bundler like webpack.
 
But the framework uses the [ESM](https://cdn.jsdelivr.net/npm/@ecl/preset-ec/+esm) to install it, which causes 2 issues with the ECL:

1. As you can check in the [link](https://cdn.jsdelivr.net/npm/@ecl/preset-ec/+esm) the var name is replaced from ECL to 'e' and because it is an IIEF, it's not possible to import it properly and use it on the project;
2. The images like logos are not available on it, because those images are not required in any file inside the package. I have tried to import directly for example the [@ecl/resources-ec-logo](https://cdn.jsdelivr.net/npm/@ecl/resources-ec-logo/) but it has no [ESM](https://cdn.jsdelivr.net/npm/@ecl/resources-ec-logo/+esm).

For tests purpose, I've created a package called [preset-ec-bridge ](https://www.npmjs.com/package/preset-ec-bridge?activeTab=code) which basically does a copy of the ecl-ec.js and replaces the 'var ECL' to 'export var ECL' to fix the first issue and also I've added an CSS file  (src/styles.css) adding those images there. With those changes, is possible to use it correctly inside the project with AssetMapper/importmap.

The issue with that approach is that we should maintain and update it when we have new ECL releases. Could you check if is possible a solution directly on the ECL project?

Thank you,
Diogo

**Comment by planctus** [comment]
Mmhh... @diogoslack, as you noticed, currently ECL compiles its js transpiling ESM classes to commonJs in an IIFE structure.
I understand that in your use case, it's even more problematic to deal with the IIFE structure than the commonJs code, your solution is an hack that makes ECL usable on your side, but surely not in a comfortable way. 

For images like the logos svgs, we only distribute them as assets, files, up to you to define which are the ones that you need or intend to use in your app, we did not have any prior request to access them in any different way.

Sure we can consider adding an ESM version of the distributed js, this is something we could consider doing already in v4, and potentially, although it feels a bit overkill, define an "asset" module where to export all the logos, but since we are in the process of starting the development of ECL 5 i think this could happen there and not be backported to ECL 4.

**Comment by diogoslack** [comment]
Hello @planctus,

Thank you for your prompt answer!

Do you expect to have it in the coming months or is it something that can demand more time? Just to adjust the expectations and see if we can wait for it or if is better to go with an alternative solution until there.

Thank you,
Diogo

**Comment by planctus** [comment]
ECL 5 should be released, although still in a unstable version, next year, first quarter as the deadline, so potentially in the first months of 2025.
If we have the chance to include at least the script in ESM in v4, this could happen earlier, but i don't really have a plan currently about next releases in the current major version.

**Comment by diogoslack** [comment]
Hello @planctus,

Okay, fair enough.

Thank you!
Diogo
