### ISSUE TITLE
Menu not working alongside Inpage navigation

### ISSUE THREAD

**Issue by jcastro-malet** [ec-europa/europa-component-library#603]
Hello
I've found this problem working with the Menu component in the same page as In page navigation component. The test was done with Google Chrome 62

### Expected behavior
Menu component should work alongside any other component.

### Actual behavior
The component Menu is not working right along the inpage navigation component. When the menu has second level options, and we add an inpage navigation, the menu stops opening.

### Steps to reproduce the issue
- Create a page with a Menu, having some option with 2 levels
- Add an inpage navigation
- Call the javascript functions when the document is ready
ECL.megamenu();
ECL.initExpandables();
ECL.navigationInpages();

The moment the function "initExpandables" is called, the menu stops working. It doesn't work either if you call "megamenu" at the last position.
The only way I've found to prevent this problem is calling ECL.megamenu() again after loading the expandables and the inpage navigation, loading it twice.

I attach a test case of this problem
[Test.zip](https://github.com/ec-europa/europa-component-library/files/1807254/Test.zip)

Thank you

**Comment by degliwe** [comment]
@jcastro-malet thank you for this elaborated feedback. this is a defect we have a ticket for this INNO-849 in our jira.
We are prioritizing it.

**Comment by alessandro-russo** [comment]
Ciao guys,
first of all thanks for you great work on all this stuff!

A short comment on this issue. In general ``ECL.initExpandables();`` may "conflict" with any other component having an "expandable behaviour", such as the accordion. This comes from the default context (``document``) and selector (``'[aria-controls][aria-expanded]'``) used by ``initExpandables()``.

Although some options are a bit hidden in the documentation, up to now I've always prevented conflicts by trying to narrow the scope of the context or selector when Menu, accordion, inpage navigation and expandables coexist.

@jcastro-malet in the specific scenario of your test case, something like
```
ECL.megamenu();
ECL.initExpandables('.ecl-navigation-inpage__trigger');
ECL.navigationInpages();
```
should avoid that ``initExpandables()`` affects the menu.

Anyway, I'm sure you'll come up with a solution that will prevent conflicts "by default" :)

**Comment by jcastro-malet** [comment]
@alessandro-russo Thank you for the idea. I'll test it, as I think it's cleaner than my current solution

**Comment by yhuard** [comment]
Thank you @alessandro-russo for your help here, we appreciate it 👍 

Indeed, `ECL.megamenu()` internally triggers the expandable behavior for its own use. As a consequence, with the following code, the expandable component within the megamenu gets expanded and collapsed right after:

```
ECL.megamenu();
ECL.initExpandables();
```

This is something we have to sort out internally but as @alessandro-russo stated, you can already avoid those collisions by specifically targetting `ECL.initExpandables('.ecl-navigation-inpage__trigger');`, thus not messing with the already initialized expandable from the megamenu. 

Our lack of consistency is to blame here, because one of our components embeds the expandable behavior while the other has to be explicitly initialized. We will fix this before the next major version.
